### ISSUE TITLE
Registration of ESA Account and Access Request of m2m Service

### ISSUE THREAD

**Issue by KKEE151** [jpalomav/SAET_master#1]
Heyy guys, I have some questions about the registration of ESA Account and Access Request of m2m service mentioned in Section 3. 

1. I noticed that the ESA account does not have a username, should I replace the asterisks with my email address instead? (for the sp_config.py, 'USER_ESA').

2. Next, may I know what I should input for the Datasets Required, Data Product Required and Scenes required when filling out the access request form for m2m service provided by the USGS?

**Comment by jpalomav** [comment]
Hi. First of all we would thank you for using SAET.
Regarding your questions:
1. Yes, you need replace the asterisks symbols with your user and pasword
to access ESA (Sentinel-2) and USGS (Landsat) services. Take into account
that for m2m service (USGS) they last some days to accept your request.

2. Regarding the m2m api registration, it is a form just to know some
information about the users. So, you can fill out the fields required
witting down something like that:
 Product required: Landsat series,
Type of escenes: Landsat 8 and 9.
Number of escenes by year: 100. I think this parameter is only for
statistical purposes and I don't think this number have negative effects (I
don't think the cut the service once you have downloaded 100 images, but I
am not sure. You always can use a biger number of images).

I hope our answers help you to solve your doubts.

Best regards,

Jesus Palomar. SAET team

**Comment by KKEE151** [comment]
Thank you for clearing my doubts! 
Btw, may I know if SAET works in regions other than Europe? (which are not covered by the European beaches)
I tried running the Extraction process using the default settings for Japan (54SVF), but it says that no results can be obtained

<img width="854" alt="Screenshot 2023-12-14 170718" src="https://github.com/jpalomav/SAET_master/assets/153714789/a6706476-8d93-4a17-b554-1c58caede689">

**Comment by jpalomav** [comment]
Hi.

SAET was designed originally to work on european coasts, but can be adapted
to any area of the world. It the readme file (in github) there is a section
called "Considetations" and there you can find the next paragrahp: "The
shapefiles inside the folder “aux_data” are mandatory to make the tool
work. If modifications (removing, updating) in the “beaches.shp” file are
needed, do not forget to maintain the field “BEACH_CODE” with unique
identifiers". That means that if you open the layer beaches.shp in a GIS
tool (QGIS for example), you will see that this layer is a polygon layer
containing all areas classified as beaches along all european coasts. If
you want to analize other area in other place outside Europe, you can add a
new polygon to this layer. The only thing you have to take into account is
that each polygon have a code (stored in a field named "BEACH_CODE"). You
must be sure that the code for the new polygon is unique and there is not
another polygon with the same code. That is all. SAET uses these layer to
focus the shoreline extraction inside this polygons, so, if you don't have
any polygon in your scene, SAET wont be able to obtain the shoreline.

I hope this informtation will be useful for you.

Best regards,

Jesus Palomar. SAET team

**Comment by barwin814** [comment]
Hi, I'm a new college student and I'm looking for some basic instruction.
I want to use this tool to process the coastlines of continents other than Europe, and to do so I need to change the scope, so what do I need to pay attention to when modifying the beach.shp file? When I do the processing, I generate a temp file with a bb300.shp file in it, do I just need to simply put this file into the aux_data folder, and then I can use it as a tool to process the coastlines of continents other than Europe.
